### ISSUE TITLE
Toolchain out of date (c++ issues)

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/keystone#195]
This arose from https://github.com/keystone-enclave/keystone/issues/194
The issue seems to be that the version of the c++ standard libraries shipped in our buildroot image is subtlety different from what our toolchain expects.
This results in very strange behavior (e.g. the example in #194 of printing `-500` rather than `500`)

**Comment by dayeol** [comment]
FYI, https://github.com/riscv/riscv-gnu-toolchain/issues/475

**Comment by dkohlbre** [comment]
Looks like this is actually an issue with old toolchains. We'll look to move to a newer one.

**Comment by zkh2018** [comment]
> Looks like this is actually an issue with old toolchains. We'll look to move to a newer one.

Yes, It is actually an issue. I encountered several problems similar to #194. So I tried to compile builderoot with the latest version of tool chain, but failed. The problems are as follows:
```
riscv64-unknown-linux-gnu-ld: syscall.o:(.bss+0x0): multiple definition of `runtime_va_start'; boot.o:(.bss+0x0): first defined here
```
Therefore, I hope you can upgrade the tool chain as soon as possible to better support C++.

**Comment by dkohlbre** [comment]
I'll keep some progress notes here:
A toolchain of `256a410` and buildroot of `60e3a096` seems like a plausible candidate for upgrades. It requires a couple patches to Eyrie (the above comment is running into these) and changing some buildroot config values.
Currently the driver is crashing with this combination. Until we get everything building cleanly we can't bump toolchains.

**Comment by dayeol** [comment]
gcc 9.2.0 seems to work with buildroot 2019.08

**Comment by dayeol** [comment]
@dkohlbre what did you mean by "the driver is crashing"? Was it crashing when allocating with CMA or was it just not compiling?

**Comment by dkohlbre** [comment]
It was crashing (100% of the time) during execution of the test programs. The crash was occurring because the CMA allocation (for the shared buffer only) failed sometime AFTER the driver finished its part (correctly). Then the user-space program would get a failure result from the allocation request (and at the time did not handle that failure safely, thus crashing.)

**Comment by dayeol** [comment]
Could you paste the outputs if you have them?

**Comment by dkohlbre** [comment]
I don't have access to that machine right now, sorry.

**Comment by dayeol** [comment]
Resolved
